# Generated by Django 2.0.7 on 2018-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_url', models.CharField(max_length=2048)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
