# Generated by Django 2.0.7 on 2018-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
